### ISSUE TITLE
'FakePaymentsView' object has no attribute 'request'

### ISSUE THREAD

**Issue by blacking** [cypreess/django-plans#51]
Hello,

i got this error with django 1.4.7 and django-plans last version. Debug show me these lines as error:
**

**def get_queryset(self):
        return super(FakePaymentsView, self).get_queryset().filter(user=self.request.user)

def dispatch(self, _args, *_kwargs):
    if not getattr(settings, 'DEBUG', False):
         return HttpResponseForbidden('This view is accessible only in debug mode.')
    *_self.object = self.get_object()
    return super(FakePaymentsView, self).dispatch(_args, **kwargs)

django-plans works fine with dj 1.6.2 and demo folder, but with 1.4.7 version these two methods ask me to resolve an error hard for me.

Can you help me

thanks
marco

**Comment by Alir3z4** [comment]
This is an old issue from unsupported version of Django.
If this happens please feel free to re-open.
